config/routes.rb
YaYoCom::Application.routes.draw do



  Mercury::Engine.routes
  resources :pages do
    member { post :mercury_update }
  end

  get "welcome/index"
  get "welcome/preview"
  get "welcome/facebook"



  match 'offerte' =>"promos#index"  ,:via=>:get
  match 'home'    => 'promos#index' , :via => :get
  match 'login'   => "welcome#index", :via => :get

  resources :invitations
  match '/invito/:invitation_token' =>"welcome#index",:as=>'invite'
  match '/facebook_connect' =>"welcome#facebook",:as=>'from_facebook'



  root :to => "promos#index"

  resources :yayo_experience ,:controller=>:posts, :as=>"posts"
  match "yayo_experience/blog/:tag_name" => "posts#tag", :as => "tag_posts"




  namespace :admin do
    #resource :cms_settings
    resources :posts


    resources :home_resources  do
         match 'publish' => 'home_resources#publish', :via => :get
         match 'preview' => 'home_resources#preview', :via => :get
         match 'clearimage/:scope' => 'home_resources#clearimage', :via => :delete,:as=>:clearimage
    end
  end



end

app/views/admin/pages/_form.html.erb
<div class="yui-gc">
  <div class="yui-u first">
    <%- locals = {:f => f} -%>
    <%= hook :admin_page_form_left, locals do %>
      <%= f.field_container :title do %>
        <%= f.label :title, t("cms.title") %> <span class="required">*</span><br />
        <%= f.text_field :title, :class => 'fullwidth title'  %>
        <%= f.error_message_on :title %>
      <% end %>

      <%= f.field_container :permalink do %>
        <%= f.label :permalink, t("cms.permalink") %> <span class="required">*</span><br />
        <%= f.text_field :permalink, :class => 'fullwidth title'  %>
        <%= f.error_message_on :permalink %>
      <% end %>

      <%= f.field_container :body_raw do %>
        <%= f.label :body_raw, t("cms.body")%><br />
        <%= f.text_area :body_raw, {:cols => 60, :rows => 4, :class => 'fullwidth'} %>
        <%= f.error_message_on :body_raw %>
      <% end %>
    <% end %>
  </div>
  <div class="yui-u">
    <%= hook :admin_page_form_right, locals do %>
    
      <p>
        <%= f.label :is_active, t("cms.status")%><br />

        <%= f.radio_button :is_active, 1 %><%= t("cms.publish") %> 
        <%= f.radio_button :is_active, 0 %><%= t("cms.draft") %>
        <%= f.error_message_on :is_active%>
      </p>
      <h2><%= t("metadata") %></h2>
      <%= hook :admin_page_form_meta, locals do %>
        <p>
          <%= f.label :meta_keywords, t("cms.meta_keywords")%><br />
          <%= f.text_field :meta_keywords, :class => 'fullwidth' %>
        </p>
        <p>
          <%= f.label :meta_description, t("cms.meta_description")%><br />
          <%= f.text_field :meta_description, :class => 'fullwidth' %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/pages/edit.html.erb
<h1><%= t("cms.editing_page") + " &ldquo;#{@page.title}&rdquo;" %></h1>

<%= form_for(@page, admin_post_path(@page), :html => { :method => :put, :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

app/views/admin/pages/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li id="new_ot_link">
      <%= button_link_to t("cms.new_page"), new_object_url,
                         {:remote => true,
                         :icon => 'add',
                         'data-update' => 'new-page'} %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= "#{t('actions.listing')} #{t('pages')}" %></h1>

<%= image_tag "spinner.gif", :plugin=>"spree", :style => "display:none", :id => 'busy_indicator' %>
<div id="new-page"></div>


<table class="index">
  <tr>
    <%= hook :admin_pages_index_headers do %>
      <th><%= sort_link @search , :title, t("cms.title") %></th>
      <th><%= sort_link @search, :date,  t("cms.date") %></th>
    <% end %>
    <th>
      <%= hook :admin_pages_index_header_actions %>
    </th>
  </tr>

<% @collection.each do |page| %>
  <%- locals = {:page => page} -%>
  <tr>
    <%= hook :admin_pages_index_rows, locals do %>
      <td><%= link_to h(page.title), [:edit,:admin,page] %> (<%= page.is_active == 1 ? t("cms.published") : t("cms.draft") %>) </td>
      <td><%= (page.published_at.blank? ? page.updated_at : page.published_at).strftime("%B %d, %Y at %I:%M%p") %></td>
    <% end %>
    <td class="actions">
      <%= hook :admin_pages_index_row_actions, locals do %>
        <%= link_to_edit page %>
        &nbsp;
        <%= link_to_delete page %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>
<%=  paginate @collection %>

<%= content_for :sidebar do %>

  <%= form_for @search do |f| %>
    <div class="box">
      <h3><%= t(:search) %></h3>

      <%- locals = {:f => f} -%>
      <%= hook :admin_pages_index_search, locals do %>
        <p>
          <label><%= t("cms.title") %></label><br />
          <%= f.text_field :title_contains, :size => 15 %>
        </p>
        
        <label><%= t("cms.published_date_range") %></label><br />
        <div class="yui-g date-range-filter">
          <div class="yui-u sub-field first">
            <%= f.unobtrusive_date_text_picker :published_at_after %><br />
            <label class="sub"><%= t("start") %></label>
          </div>
          <div class="yui-u sub-field">
            <%= f.unobtrusive_date_text_picker :published_at_before %><br />
            <label><%= t("stop") %></label>
          </div>
        </div>

        <p>
          <%= f.check_box :is_active, {:style => "vertical-align:middle;"}, "1", ""  %>
          <label>
            <%= t("cms.show_only_published_pages") %>
          </label>
        </p>
      <% end %>

      <%= hook :admin_pages_index_search_buttons, locals do %>
        <p class="form-buttons">
          <%= button t("search") %>
        </p>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/admin/pages/new.html.erb
<%= render "shared/error_messages", :target => @page %>

<%= form_for(:page,  :url => collection_url, :html => { :multipart => true }) do |f| %>
<fieldset>

  <%= f.field_container :title do %>
    <%= f.label :title, t("cms.title") %> <span class="required">*</span><br />
    <%= f.text_field :title, :class => 'fullwidth title'  %>
    <%= f.error_message_on :title %>
  <% end %>

  <div class="yui-gb">
    <div class="yui-u first">

      <%= f.field_container :body_raw do %>
        <%= f.label :body_raw, t("cms.body")%> <span class="required">*</span><br />
        <%= f.text_area :body_raw, {:cols => 120, :rows => 4, :class => 'fullwidth'} %>
        <%= f.error_message_on :body_raw %>
      <% end %>

    </div>

  </div>

  <%= render :partial => 'admin/shared/new_resource_links' %>

</fieldset>
<% end %>