config/routes.rb
YaYoCom::Application.routes.draw do



  Mercury::Engine.routes
  resources :pages do
    member { post :mercury_update }
  end

  get "welcome/index"
  get "welcome/preview"
  get "welcome/facebook"



  match 'offerte' =>"promos#index"  ,:via=>:get
  match 'home'    => 'promos#index' , :via => :get
  match 'login'   => "welcome#index", :via => :get

  resources :invitations
  match '/invito/:invitation_token' =>"welcome#index",:as=>'invite'
  match '/facebook_connect' =>"welcome#facebook",:as=>'from_facebook'



  root :to => "promos#index"

  resources :yayo_experience ,:controller=>:posts, :as=>"posts"
  match "yayo_experience/blog/:tag_name" => "posts#tag", :as => "tag_posts"




  namespace :admin do
    #resource :cms_settings
    resources :posts


    resources :home_resources  do
         match 'publish' => 'home_resources#publish', :via => :get
         match 'preview' => 'home_resources#preview', :via => :get
         match 'clearimage/:scope' => 'home_resources#clearimage', :via => :delete,:as=>:clearimage
    end
  end



end

app/views/shared/_cms_content_for.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag 'sass/cms' %>
<% end %>

<%= content_for :sidebar do %>
  <%= render :partial => 'shared/recent_articles'%>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
	<p class="link">
	<!--<a href="#">Registrazione</a> |-->
	<a href="#">Chi siamo</a> |
	<a href="#">Come funziona</a> |
	<a href="#">Condizioni di vendita</a> |
	<a href="#">Privacy</a> |
	<a href="#">Contatti</a> |
	<a href="#">Fornitori</a> |
	<a href="#">Magazine</a>
	</p>
	<p>Yayo S.p.A sede Legale in Via Buonarroti, 8 20145 Milano - Capitale sociale &euro;306.600 i.v., Codice Fiscale/P.I. n. 05249460964, REA Milano n. 1807720</p>
</div>

app/views/shared/_head.html.erb
    <title>

            <% if content_for?(:title) %>
                <%=yield :title%>
            <%else%>
                 <%=title%>
            <%end%>
    </title>
    <meta http-equiv="Content-type" content="text/html;charset=iso-8859-15">
	<%== meta_data_tags %>
    <%= stylesheet_link_tag    "store/all" %>
    <%= javascript_include_tag "store/all" %>
    <%= javascript_include_tag "jquery.boxy.js" %>
    <%= javascript_include_tag "jquery.blockui.js" %>



    <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
<!--[if lt IE 9]>
       <%= stylesheet_link_tag    "ie" %>
<![endif]-->
<!--[if lte IE 8]>
        <%= stylesheet_link_tag    "ie" %>
<![endif]-->

    <%= yield :head %>

app/views/shared/_header.html.erb
<div class="header"  id="header" data-hook style="background-image: url(<%=home.head_background.url(:top)%>)" >
        <div class="top">
            <a href="<%=root_path%>" title="<%=t(:homepage)%>"><%=image_tag home.logo.url(:top),:width=>"284",:height=>"92", :alt=>"yayo",:class=>"logo"%></a>
            <p><%=t(:profile_welcome)  unless current_user.nil?%> <b><%=current_user.email unless current_user.nil?%></b><br><a href="#"><%=t(:profile_change)  unless current_user.nil?%></a>
            <% if current_user and current_user.roles.where(:name => :admin).present? %>
                <br><%=link_to t(:access_admin), admin_path %>
                  <% unless @page.nil? %>
                |
                  <%= link_to t(:edit_page), "/editor" + request.path, id: "edit_link", data: { save_url: mercury_update_page_path(@page) } %>
                      <%end%>
             <%end%>
            </p>
        </div>
</div>

app/views/shared/_home_resource_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_home_resource_sub_tabs">
    <%= tab :home_resources, :label => t(:home_resources), :match_path => '/home_resources' %>
    <%= tab :articles, :label => t(:articles), :match_path => '/articles' %>
  </ul>
<% end %>

app/views/shared/_nav_bar.html.erb
<%@menu.each do|value|%>
    <p <%="class='active'" if request.env['PATH_INFO'].include? value[:link] %>><%=link_to t(value[:name]),value[:link]%></p>
<%end%>

app/views/shared/_privacy.html.erb
<fieldset>
	<legend><%=t(:registration_accept)%></legend>

	<p>
	<textarea cols="20" rows="5" readonly="" style="width:100%"><%=t(:registration_terms)%></textarea></p>
	<p><label><%=t(:registration_approve)%></label>
       <input type="checkbox" name="user[accept_terms_and_privacy]" value="1">

	</fieldset>

app/views/shared/_promo.html.erb
<%=image_tag home.leaderboard.url(:top), :width=>"963", :height=>"85",:alt=>"promo"%>

app/views/shared/_recent_articles.html.erb
<h3><%= t("recent_posts") %></h3>
<ul>
<% post_link_list().each do |link| -%>
  <li><%= link_to link.name, link.url %></li>
<% end -%>
<li><%= link_to posts_path(:format => 'rss') do -%><%= image_tag('icons/feed.gif', :alt => "#{t("posts")} RSS", :size => '16x16') %> RSS Feed <%- end -%></li>
</ul>

app/views/shared/_side_bar.html.erb
<h1 class="lbl"><%=image_tag "store/arrow1.png", :width=>"11", :height=>"12" ,:alt=>"arrow",:class=>"arrow green"%>prossimamente</h3>
            <p class="intro">Scopri le prossime uscite in esclusiva per YAYO</p>

                <div class="inda1">
                <div class="data">
                <p>MAG<span>29</span></p>
                </div>
                <ul>
                <li><a href="brand.html">Nomination<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Mc Kenzy<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Penn<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Rich by Woolrich<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">NK Home<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Peninsula<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Canguro<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                </ul>
                </div>

                <div class="inda1">
                <div class="data">
                <p>MAG<span>11</span></p>
                </div>
                <ul>
                <li><a href="brand.html">Wanted<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Present Time<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Blunauta<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">De Kuba<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Guardini<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Bosch<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                <li><a href="brand.html">Dremel e Skil<%=image_tag "store/lente.png" ,:alt=>"lente"%></a></li>
                </ul>
                </div>

                <hr>

                <h1 class="lbl"><%=image_tag "store/arrow1.png",:width=>"11" ,:height=>"12" ,:alt=>"arrow" ,:class=>"arrow cyan"%>yayo mobile</h3>
                <div class="app">
                <p style="margin-bottom:15px;">Scarica la app e accedi a promozioni e prevendite esclusive!<br><a href="#" style="float:right;">Scarica gratis</a></p>
                <a href=""><%=image_tag "store/appyayo.png", :width=>"199", :height=>"66",:alt=>""%></a>
                <a href=""><%=image_tag "store/android-yayo.png" ,:width=>"199",:height=>"66",:alt=>""%></a>
                </div>

app/views/shared/_social_link.html.erb
<p class="">
                <a href="#" title="vai alla nostra pagina su"><%=image_tag "store/facebook.png", :width=>"16",:height=>"16",:alt=>"send"%></a>
                <a href="#" title="vai alla nostra pagina su"><%=image_tag "store/twitter.png", :width=>"16",:height=>"16",:alt=>"send"%></a>
                <a href="#" title="segnala questo prodotto ad un amico"><%=image_tag  "store/send.png", :width=>"16",:height=>"16",:alt=>"send"%></a>
    </p>

app/views/shared/_socials.html.erb
<% AuthenticationMethod.where(:environment => ::Rails.env).each do |user| %>
  <%= link_to user_authentication_omniauth_authorize_path(user.preferred_provider.to_sym),:style=>"font-size:13px;float:right" do %>
            <%=t(:social_access,:provider=>user.preferred_provider) if user.active %>
           <%=  image_tag("store/social/#{user.preferred_provider}_32.png",
                            :style=>"vertical-align:middle" ,
                            :size => "32x32",
                            :alt => "#{user.preferred_provider}") if user.active%>

  <%end%><br>
<% end %>
    <br>

app/views/shared/_store_menu.html.erb
<li><%= link_to t("home") , root_path %></li>
<% Page.all.each do |page| %>
<li><%= link_to page.title, page %></li>
<% end %>
<li class="cart-indicator"><%= link_to_cart %></li>