config/routes.rb
YaYoCom::Application.routes.draw do



  Mercury::Engine.routes
  resources :pages do
    member { post :mercury_update }
  end

  get "welcome/index"
  get "welcome/preview"
  get "welcome/facebook"



  match 'offerte' =>"promos#index"  ,:via=>:get
  match 'home'    => 'promos#index' , :via => :get
  match 'login'   => "welcome#index", :via => :get

  resources :invitations
  match '/invito/:invitation_token' =>"welcome#index",:as=>'invite'
  match '/facebook_connect' =>"welcome#facebook",:as=>'from_facebook'



  root :to => "promos#index"

  resources :yayo_experience ,:controller=>:posts, :as=>"posts"
  match "yayo_experience/blog/:tag_name" => "posts#tag", :as => "tag_posts"




  namespace :admin do
    #resource :cms_settings
    resources :posts


    resources :home_resources  do
         match 'publish' => 'home_resources#publish', :via => :get
         match 'preview' => 'home_resources#preview', :via => :get
         match 'clearimage/:scope' => 'home_resources#clearimage', :via => :delete,:as=>:clearimage
    end
  end



end

app/models/home_resource.rb
class HomeResource < ActiveRecord::Base

  has_attached_file :claim, :styles => { :thumb => ["338x19", :png]}
  has_attached_file :iconic, :styles => {:thumb => ["141x79", :png] }
  has_attached_file :background, :styles => { :thumb => ["141x44", :png]}
  has_attached_file :logo, :styles => {:top=>["284x92",:png], :thumb => ["141X50", :png]}
  has_attached_file :leaderboard, :styles => { :top => ["963x85", :png],:thumb => ["141X44", :png]}
  has_attached_file :head_background, :styles => { :top => ["1380x113", :png],:thumb => ["141X44", :png]}



  validates_attachment_content_type :claim,{:content_type=> ["image/png","image/jpg","image/jpeg"], :message => I18n::t('flash.image_not_correct_content_type',:locale=>:it), :if => "claim_file_name_changed?"}
  validates_attachment_content_type :background,{:content_type=> ["image/png","image/jpg","image/jpeg"], :message => I18n::t('flash.image_not_correct_content_type'), :if => "background_file_name_changed?"}
  validates_attachment_content_type :logo,{:content_type=> ["image/png","image/jpg","image/jpeg"] , :message => I18n::t('flash.image_not_correct_content_type'), :if => "logo_file_name_changed?"}
  validates_attachment_content_type :iconic,{:content_type=> ["image/png","image/jpg","image/jpeg"], :message => I18n::t('flash.image_not_correct_content_type'), :if => "iconic_file_name_changed?"}
  validates_attachment_content_type :leaderboard,{:content_type=> ["image/png","image/jpg","image/jpeg"], :message => I18n::t('flash.image_not_correct_content_type'), :if => "leaderboard_file_name_changed?"}
  validates_attachment_content_type :head_background,{:content_type=> ["image/png","image/jpg","image/jpeg"], :message => I18n::t('flash.image_not_correct_content_type'), :if => "head_background_file_name_changed?"}



  validates_attachment_size :claim, :less_than => 70.kilobytes , :message => I18n::t('flash.image_size',:size=>"70KB"),  :if => Proc.new { |imports| !imports.claim.file? }
  validates_attachment_size :background, :less_than => 70.kilobytes , :message => I18n::t('flash.image_size',:size=>"70KB"), :if => "background_file_name_changed?"
  validates_attachment_size :logo, :less_than => 100.kilobytes    , :message => I18n::t('flash.image_size',:size=>"40KB")      , :if => "logo_file_name_changed?"
  validates_attachment_size :iconic, :less_than => 70.kilobytes   , :message => I18n::t('flash.image_size',:size=>"70KB")     ,  :if => Proc.new { |imports| !imports.iconic.file? }
  validates_attachment_size :leaderboard, :less_than => 70.kilobytes   , :message => I18n::t('flash.image_size',:size=>"70KB")     ,  :if => Proc.new { |imports| !imports.leaderboard.file? }
  validates_attachment_size :head_background, :less_than => 20.kilobytes   , :message => I18n::t('flash.image_size',:size=>"20KB")     ,  :if => Proc.new { |imports| !imports.head_background.file? }

  # validates_attachment_presence  :iconic  , :message => I18n::t('flash.image_mandatory')
  #validates_attachment_presence  :background    , :message => I18n::t('flash.image_mandatory')
  #validates_attachment_presence  :logo       , :message => I18n::t('flash.image_mandatory')
end

app/controllers/admin/home_resources_controller.rb
class Admin::HomeResourcesController <  Admin::ResourceController
  resource_controller

  def index
    @object = HomeResource.where(:preview=>true).first
    @object  = HomeResource.new if @object.nil?
    @object.preview=true

    @object.save if HomeResource.where(:preview=>true).empty?
    HomeResource.create :preview=>false if HomeResource.where(:preview=>false).empty?

    render :edit
    #redirect_to :action=>:edit
  end

  def show
    render :edit
  end
  #def edit
  #  @hr = HomeResource.first
  #  @hr  = HomeResource.new if @hr.nil?
  #end



  def clearimage
        @object = HomeResource.where(:id=>params[:home_resource_id]).first
        @object.send(params[:scope]).clear
        @object.send(params[:scope]).destroy
        @object.send(params[:scope],nil)
        @object.save
        @scope = params[:scope]
        respond_with(@scope) do |format|
          format.js  {render :layout => false}
        end
  end

  def publish
      expire_fragment :header
      expire_fragment :home
      expire_fragment :promo_top

      @object = HomeResource.where(:id=>params[:home_resource_id]).first
      published = HomeResource.where(:preview=>false).first
      published.destroy  unless published.nil?
      nuovo = HomeResource.new :title=>@object.title,:iconic=>@object.iconic,:background=>@object.background,  :logo=>@object.logo,
                                :leaderboard=>@object.leaderboard, :head_background=>@object.head_background,
                                :claim=>@object.claim,:preview=>false



      if (nuovo.save)
        flash[:notice] =flash_message_for(@object, :wp_online)
        respond_with(@object) do |format|
          format.html { redirect_to location_after_save }
          format.js   { render :layout => false }
        end
      else

        redirect_to location_after_save
      end

  end



end

app/helpers/home_resources_helper.rb
module HomeResourcesHelper
end

app/views/admin/home_resources/_form.html.erb
<%= f.inputs do %>
    <div id="tab-title" class="tabs">
        <%=f.input  :title,:label=>t(:claim)%>
    </div>

    <%=render :partial=>"uploadfragment", :locals => { :f => f,:scope=>:background,:size=>"70kb"}%>
    <%=render :partial=>"uploadfragment", :locals => { :f => f,:scope=>:logo,:size=>"100kb"}%>
    <%=render :partial=>"uploadfragment", :locals => { :f => f,:scope=>:iconic,:size=>"70kb"}%>
    <%=render :partial=>"uploadfragment", :locals => { :f => f,:scope=>:leaderboard,:size=>"70kb"}%>
    <%=render :partial=>"uploadfragment", :locals => { :f => f,:scope=>:head_background,:size=>"20kb"}%>

<% end %>

app/views/admin/home_resources/_uploadfragment.html.erb
   <div class="gray tabs" id="tab-<%=scope%>">
     <h3 style="margin-left:20px"><%= t(scope)%></h3>
    <table class="center" style="border-collapse: collapse">
        <tbody><tr>
          <td>
                <div class="profile-image">
                        <%=t(:wp_no_image) if @object.send("#{scope}_file_name").nil?%>
                        <%= image_tag  @object.send(scope).url(:thumb) unless @object.send("#{scope}_file_name").nil?%>
                <div>
               <div class="image-reset">
               <%= link_to t(:wp_reset_image),admin_home_resource_clearimage_path(@object,scope) ,:format=>:json, :confirm => t(:wp_confirm), :method => :delete, :remote=>true,:class=>"ajax-#{scope}"  unless @object.send("#{scope}_file_name").nil?%>
               </div>
               </div>
                    </div>
          </td>
          <td>
          <div class="">
            <div class="">
              <div id=""><strong><%=t(:wp_upload_action,:size=>size)%> </strong>
              <%= f.input scope , :as=>:file,:label=>false %>
              </div>
           </div>
            <div>
              <strong><%=t(:wp_content_type,:content=>"jpg o png")%></strong>
              <br> <br>
              <div style="float:right">
                <%= button t("actions.update"), nil, "submit"%>
                <%= t("or") %> <%= link_to t("actions.cancel"), admin_home_resources_path %>
                </div>
            </div>


          </div>
          </td>
        </tr>
        </tbody>
    </table>
    </div>

app/views/admin/home_resources/clearimage.js.erb
$("#tab-<%=@scope%> .image-reset").html(<%=t(:wp_no_image)%>);

app/views/admin/home_resources/edit.html.erb
<%= stylesheet_link_tag 'formtastic', 'formtastic_changes'  %>
<%= javascript_include_tag 'admin/spree_welcomepage' %>
<%= render "shared/error_messages", :target => @object %>
<h1><%= t("editing_welcome_page") %></h1>
<div class="toolbar">

               <%= button_link_to t(:publish), admin_home_resource_publish_path(@object) %>
               <%= button_link_to_function t(:preview), "preview()" %>
               <%= button_link_to_function t("actions.update"), "$('form.home_resource').submit()" %>
   </div>
<div class="page clear">
<div class="sidebar">
      <h3>Seleziona operazione</h3>
     <ul>
       <li><a href="#" class="tab-selector" onclick="$('.tabs').hide(); $('#tab-title').show('fadein');return false;"><span><%=t(:claim)%></a></span></li>

     <%[:background,:logo,:iconic,:leaderboard,:head_background].each do|xs|%>
              <li><a href="#" class="tab-selector" onclick="$('.tabs').hide(); $('#tab-<%=xs%>').show('fadein');return false;"><span><%=t(xs)%></a></span></li>
     <%end%>
         </ul>
    </div>

         <div class="content">



               <br><br>
               <%= semantic_form_for([:admin, @object]) do |f| %>

                     <%= render :partial => "form", :locals => { :f => f  } %>
            <% end %>

    </div>

                 </div>