config/routes.rb
YaYoCom::Application.routes.draw do



  Mercury::Engine.routes
  resources :pages do
    member { post :mercury_update }
  end

  get "welcome/index"
  get "welcome/preview"
  get "welcome/facebook"



  match 'offerte' =>"promos#index"  ,:via=>:get
  match 'home'    => 'promos#index' , :via => :get
  match 'login'   => "welcome#index", :via => :get

  resources :invitations
  match '/invito/:invitation_token' =>"welcome#index",:as=>'invite'
  match '/facebook_connect' =>"welcome#facebook",:as=>'from_facebook'



  root :to => "promos#index"

  resources :yayo_experience ,:controller=>:posts, :as=>"posts"
  match "yayo_experience/blog/:tag_name" => "posts#tag", :as => "tag_posts"




  namespace :admin do
    #resource :cms_settings
    resources :posts


    resources :home_resources  do
         match 'publish' => 'home_resources#publish', :via => :get
         match 'preview' => 'home_resources#preview', :via => :get
         match 'clearimage/:scope' => 'home_resources#clearimage', :via => :delete,:as=>:clearimage
    end
  end



end

app/models/post.rb
class Post < ActiveRecord::Base
  cattr_reader :per_page
  #@@per_page = Spree::Config[:cms_posts_per_page]
  #attr_accessible :user_id, :title, :body_raw, :published_at, :is_active, :permalink, :tag_list, :excerpt, :commentable, :meta_keywords, :meta_description
  paginates_per Spree::Config[:cms_posts_per_page]
  is_taggable :tags


  has_attached_file :immagine, :styles => {:thumb => ["174x20", :png]}

  belongs_to :user
  before_validation :format_markup
  #before_validation :generate_permalink
  before_validation :published
  
  make_permalink :with => :title
   
  validates_presence_of :title, :message => 'required'
  validates_presence_of :body, :message => 'required'
  validates_uniqueness_of :permalink 
  
  default_scope order('published_at DESC')
  scope :publish, where('published_at < ? and is_active = ?', Time.zone.now, 1)
  scope :tag, where(:discontinued => true)


#should be part of is_taggable
  #pulled from http://github.com/gnugeek/is_taggable/commit/10b590865f0effeed20f00e3581a7aed8a6bd3b4
  def self.find_all_tagged_with(tag_or_tags, conditions=[])
    return [] if tag_or_tags.nil? || tag_or_tags.empty?
    case tag_or_tags
    when Array, IsTaggable::TagList
      includes('tags', 'taggings').where(conditions).select { |record| tag_or_tags.all? { |tag| record.tags.map(&:name).include?(tag) } } || []
    else
      includes('tags', 'taggings').where(conditions).select { |record| record.tags.map(&:name).include?(tag_or_tags)  } || []
    end
  end
    
  def to_param
    return permalink unless permalink.blank?
    title.to_url
  end
  
  def format_markup
    if not self.body_raw.nil?
      self.body = RedCloth.new(self.body_raw,[:sanitize_html, :filter_html]).to_html
    end
  end

  #def link
  #  ensure_slash_prefix permalink
  #end
  
  def published
    #self.published_at ||= Time.now unless self.is_active == 0
    if self.is_active == 0
      if !self.published_at.blank?
          self.published_at = nil
      end
    else
      if self.published_at.blank?
          self.published_at = Time.now
      end
    end
  end
  
  def month
    published_at.strftime('%B %Y')
  end
  
#private

#  def ensure_slash_prefix(str)
#    str.index('/') == 0 ? str : '/' + str
#  end   
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  resource_controller :except => [:show]

  index.response do |wants|
    wants.html { render :action => :index }
    wants.json { render :json => @collection.to_json()  }
  end
  
  new_action.response do |wants|
    wants.html {render :action => :new, :layout => false}
  end
  
  create.before :create_before

  create.response do |wants|
    # go to edit form after creating as new post
    wants.html {redirect_to edit_admin_post_url(Post.find(@post.id)) }
  end

  update.response do |wants|
    # override the default redirect behavior of r_c
    # need to reload Post in case name / permalink has changed
    wants.html {redirect_to edit_admin_post_url(Post.find(@post.id)) }
  end

  private
  
    def collection

      unless request.xhr?
        # Note: the SL scopes are on/off switches, so we need to select "not_deleted" explicitly if the switch is off
        # QUERY - better as named scope or as SL scope?
        #if params[:search].nil? || params[:search][:deleted_at_not_null].blank?
        #  base_scope = base_scope.not_deleted
        #end
        
        #@search = Post.searchlogic(params[:search])

        @search = Post.search(params[:search])
        # @search.order ||= "ascend_by_title"
        @collection = @search.page(params[:page] ||1).per(10)
      else
        @collection = Post.search(:title_contains => params[:q] , :include => includes, :limit => 10)
        @collection.uniq!
      end

    end
    
    # set the default published and comment status if applicable
    def create_before
      return unless Spree::Config[:cms_post_status_default] || Spree::Config[:cms_post_comment_default]
      @post.is_active = Spree::Config[:cms_post_status_default]
      @post.commentable = Spree::Config[:cms_post_comment_default]
    end
  
end 

app/controllers/posts_controller.rb
class PostsController < Spree::BaseController
  before_filter :tags
  resource_controller
  actions :show, :index

   index.response do |wants|
    wants.html
    wants.rss
  end

  #prokeraround attivo
  # solo per la fase attuale, in attesa di capirnee il comportamento
  def unauthorized
    collection
    @posts=@collection
    render :index
  end

  def tag
    collection
    @posts=@collection
    render :index
  end

private
  def tags
    @tags = Tag.all
  end

  def collection

       debugger
    if params[:tag_name]
             coll  = Post.publish.joins(:tags).where(:tags=>{:name=>params[:tag_name]})
             @total = coll.count
             @collection ||= coll.page(params[:page])
    else
             @total  = Post.publish.count
             @collection ||= Post.publish.page(params[:page])
        end


  end


end 

app/views/posts/_post.html.erb
<div class="article <%="dett" if detail%>">
  <p class="rif"><%= post.published_at.strftime("%A %d.%m.%Y") %>
    <% unless post.user.nil? or post.user.display_name.blank? %> | scritto da
        <a href="#"><%= post.user.display_name %></a>
    <% end %></p>

  <div class="abstract">
    <span class="image"><%= image_tag post.immagine.url(:original), :alt=>post.title %></span>

    <h1><%= link_to_unless_current (post.title == '' ? '[Untitled]' : h(post.title)), post, {:title => post.title, :alt => "Link to #{post.title}"} %></h1>

    <p>
      <%= raw post.body_raw if detail %>
      <%= raw post.excerpt  unless detail %>
    </p>

    <p class="continua"><%= link_to '...[continua]', post, {:title => post.title, :alt => "Link to #{post.title}"}  unless detail%></p>
  </div>
  <p class="commenti"> | <%= link_to "commenti", post_path(post, :anchor => "disqus_thread") %>
    <!-- AddThis Button BEGIN -->
<span class="addthis_toolbox addthis_default_style " addthis:title="{<%= h(post.title) %>}" addthis:url="{<%= "#{posts_url}/#{post.permalink}" %>}">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</span>
  </p>
</div>

<%= raw disqus_comment_counts %>

app/views/posts/_side_bar.html.erb
 <%= content_for :sidebar do %>
     <h1 class="lbl"><%=image_tag "store/arrow1.png", :width=>"11" ,:height=>"12" ,:alt=>"arrow" ,:class=>"arrow yellow"%>YAYO Experience</h1>
                <%#render :partial=>"shared/social_link"%>
                <!--<ul class="breadcrumbs">-->
                    <!--<li class="lbl"><%=image_tag "store/arrow1.png" ,:width=>"11" ,:height=>"12",:alt=>"arrow",:class=>"arrow green"%> Sei in:</li>-->
                    <!--<li><a href="index.inside.html">Vetrina</a></li>-->
                    <!--<li><a href="brand.html">TAYLOR MADE</a></li>-->
                    <!--<li><a href="brand.html">Mazze da Golf</a></li>-->
                    <!--<li class="active"><a href="index_prodotto.html">Fairways</a></li>-->
                <!--</ul>-->


                <ul class="menucategoria">
                    <%@tags.each do |tag|%>
                        <li class="<%="active" if params[:tag_name]==tag.name%>"><a href="<%=tag_posts_url(tag.name)%>"><%=tag.name%></a></li>
                    <%end%>
                </ul>


 <% end %>

app/views/posts/index.html.erb
<%= content_for :head do %>
  <link rel="alternate" type="application/rss+xml" title="<%= t("posts") %> RSS" href="<%= posts_url(:format => 'rss') %>" />
<% end %>   


<%=render :partial=>"side_bar"%>

<%
   #controllo dell'autenticazione
   %>
<%if current_user.nil?%>

     <%=render :partial=>"welcome/registration", :locals=>{user:User.new } %>
    <%= javascript_include_tag "welcomepage.js" %>
    <script type="text/javascript">
            $(document).ready(function(){
               $("#reg").show("fadein");
            });
    </script>
<%end%>
  <h1 class="lbl">
			<%=image_tag "store/arrow1.png", :width=>"11",:height=>"12" ,:alt=>"arrow" ,:class=>"arrow yellow"%>YAYO Experience</h1>

<%if params[:tag_name].nil?%>
    <p class="emphasis"><span>Benvenuto su YAYO Experience</span><br>
    Qui potrai trovare spunti, informazioni, idee e tante offerte sul mondo della moda, ma non solo. Non perderne una!<br>
    Leggi, commenta, dì la tua...ed invita i tuoi amici!</p>
<%else%>
    <p class="emphasis"><span><%=params[:tag_name]%></span><br>

<%end%>



<div class="navigazione">
<p><b><%=@total%></b> Articoli</p>
    <%= paginate @posts  %>
</div>
<% for post in @posts %>
    <%=render :partial => post,:locals=>{:detail=>false} %>
<% end %>

<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4ed900c6579151de"></script>

app/views/posts/show.html.erb
   
 <%=render :partial=>"side_bar"%>

<%= render :partial => @post,:locals=>{:detail=>true} %>

<% if @post.commentable == 1 %>
<div id="comments">
  <%= raw disqus_thread %>
</div>
<% end %>

app/views/posts/tags.html.erb
<%= render :partial => 'shared/cms_content_for'%>

<h1><%= "'#{params[:tag_name]}' #{t("cms.posts")}" %></h1>

<div class="posts">
  <% unless @posts.empty? %>
  <%= render @posts %>
  <% else %>
  <p><%= t("cms.no_posts_found") %>.</p>
  <% end %>
</div>

<% #TODO - Localize this section %>
<p class="pagination">
  <%= link_to h('< Previous Page'), :overwrite_params => { :page => @posts.previous_page } if @posts.previous_page %>
  <%= "|" if @posts.previous_page && @posts.next_page %>
  <%= link_to h('Next Page >'), :overwrite_params => { :page => @posts.next_page } if @posts.next_page %>
</p>